local basalt = require(".libs.basalt")

local monitorLeftName = settings.get("monitor_left")
local monitorMiddleName = settings.get("monitor_middle")
local monitorRightName = settings.get("monitor_right")
local monitorTopName = settings.get("monitor_top")

if not (monitorLeftName and monitorMiddleName and monitorRightName and monitorTopName) then
	error(
		"Not all monitors were specified in the settings. " ..
		"Please use 'set monitor_left', -middle, -right and -top " ..
		"to specify the peripheral names of the monitors (e.g. 'monitor_0')."
	)
end

local monitorLeft = peripheral.wrap(monitorLeftName)
local monitorMiddle = peripheral.wrap(monitorMiddleName)
local monitorRight = peripheral.wrap(monitorRightName)
local monitorTop = peripheral.wrap(monitorTopName)
monitorLeft.setTextScale(0.5)
monitorMiddle.setTextScale(0.5)
monitorRight.setTextScale(0.5)
monitorTop.setTextScale(0.5)

local frameLeft = basalt.createFrame():setTerm(monitorLeft):setBackground(colors.black)
local frameMiddle = basalt.createFrame():setTerm(monitorMiddle):setBackground(colors.black)
local frameRight = basalt.createFrame():setTerm(monitorRight):setBackground(colors.black)
local frameTop = basalt.createFrame():setTerm(monitorTop):setBackground(colors.black)

frameLeft:addButton()
	:setText("Stabilize")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 5)
	:setPosition(2, 2)
	:onClick(buttonClickHandler)
frameLeft:addButton()
	:setText("Land")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 5)
	:setPosition(2, 8)
	:onClick(buttonClickHandler)
frameLeft:addButton()
	:setText("STOP")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 5)
	:setPosition(2, 14)
	:onClick(buttonClickHandler)
frameLeft:addButton()
	:setText("Engine")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 4)
	:setPosition(2, 20)
	:onClick(buttonClickHandler)

frameRight:addButton()
	:setText("^")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 5)
	:setPosition(2, 2)
	:onClick(buttonClickHandler)
frameRight:addButton()
	:setText("v")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 5)
	:setPosition(2, 8)
	:onClick(buttonClickHandler)
frameRight:addButton()
	:setText("<-")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(6, 5)
	:setPosition(2, 14)
	:onClick(buttonClickHandler)
frameRight:addButton()
	:setText("->")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(6, 5)
	:setPosition(9, 14)
	:onClick(buttonClickHandler)
frameRight:addButton()
	:setText("Brake")
	:setForeground(colors.green)
	:setBackground(colors.gray)
	:setForegroundState("clicked", colors.gray)
	:setBackgroundState("clicked", colors.lightGray)
	:setSize(13, 4)
	:setPosition(2, 20)
	:onClick(buttonClickHandler)

basalt.run()
