local basalt = require(".libs.basalt")
local data = require(".libs.data")
local physics = require(".libs.physics")

local monitorLeftName = settings.get("monitor_left")
local monitorMiddleName = settings.get("monitor_middle")
local monitorRightName = settings.get("monitor_right")
local monitorTopName = settings.get("monitor_top")

if not (monitorLeftName and monitorMiddleName and monitorRightName and monitorTopName) then
	error(
		"Not all monitors were specified in the settings. " ..
		"Please use 'set monitor_left', -middle, -right and -top " ..
		"to specify the peripheral names of the monitors (e.g. 'monitor_0')."
	)
end

local monitorLeft = peripheral.wrap(monitorLeftName)
local monitorMiddle = peripheral.wrap(monitorMiddleName)
local monitorRight = peripheral.wrap(monitorRightName)
local monitorTop = peripheral.wrap(monitorTopName)

local frameLeft = basalt.createFrame():setTerm(monitorLeft):setBackground(colors.black)
local frameMiddle = basalt.createFrame():setTerm(monitorMiddle):setBackground(colors.black)
local frameRight = basalt.createFrame():setTerm(monitorRight):setBackground(colors.black)
local frameTop = basalt.createFrame():setTerm(monitorTop):setBackground(colors.black)

local function setupLeft()
	monitorLeft.setTextScale(0.5)
	frameLeft:addButton()
		:setText("Stabilize")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 5)
		:setPosition(2, 2)
	frameLeft:addButton()
		:setText("Land")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 5)
		:setPosition(2, 8)
	frameLeft:addButton()
		:setText("STOP")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 5)
		:setPosition(2, 14)
	frameLeft:addButton()
		:setText("Engine")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 4)
		:setPosition(2, 20)
end

local function setupMiddle()
	monitorMiddle.setTextScale(1.0)
	frameMiddle:addLabel()
		:setText("F")
		:setPosition(2, 2)
		:setForeground(colors.white)
	local fuelBar = frameMiddle:addProgressBar()
		:setDirection("up")
		:setProgressColor(colors.lime)
		:setProgress(50)
		:setBackground(colors.gray)
		:setSize(1, 15)
		:setPosition(2, 4)
	basalt.schedule(function()
		while true do
			local fuelLevel = tonumber(data.fetchLatestRecord("fuel")) / tonumber(data.fetchLatestRecord("max_fuel"))
			fuelBar:setProgress(math.ceil(100 * fuelLevel))
			local fuelColors = { colors.red, colors.orange, colors.yellow, colors.lime, colors.green, colors.green }
			fuelBar:setProgressColor(fuelColors[1 + math.floor(fuelLevel * 5)])
			sleep(1)
		end
	end)
	frameMiddle:addLabel()
		:setText("H")
		:setPosition(4, 2)
		:setForeground(colors.white)
	local heightSlider = frameMiddle:addSlider()
		:setMax(300)
		:setStep(300)
		:setHorizontal(false)
		:setBackground(colors.lightBlue)
		:setSliderColor(colors.white)
		:setSize(1, 15)
		:setPosition(4, 4)
	local heightIndicator = frameMiddle:addLabel()
		:setText("o")
		:setPosition(4, 18)
	basalt.schedule(function()
		while true do
			local height = math.ceil(physics.getLocation().y)
			heightIndicator:setPosition(4, 18 - math.ceil((height - 60) * (15 / heightSlider:getMax())))
			sleep(1)
		end
	end)
	frameMiddle:addLabel()
		:setText("S")
		:setPosition(6, 2)
		:setForeground(colors.white)
	local powerLabel = frameMiddle:addLabel()
		:setPosition(6, 18)
		:setText("0")
		:setForeground(colors.white)
	frameMiddle:addSlider()
		:setMax(15)
		:setStep(15)
		:setHorizontal(false)
		:setBackground(colors.red)
		:setSliderColor(colors.brown)
		:setSize(1, 15)
		:setPosition(6, 4)
		:onChange("step", function(self, value)
			powerLabel:setPosition(6, 3 + value):setText(string.format("%X", 15 - value))
		end)
end

local function setupRight()
	monitorRight.setTextScale(0.5)
	frameRight:addButton()
		:setText("^")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 5)
		:setPosition(2, 2)
	frameRight:addButton()
		:setText("v")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 5)
		:setPosition(2, 8)
	frameRight:addButton()
		:setText("<-")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(6, 5)
		:setPosition(2, 14)
	frameRight:addButton()
		:setText("->")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(6, 5)
		:setPosition(9, 14)
	frameRight:addButton()
		:setText("Brake")
		:setForeground(colors.green)
		:setBackground(colors.gray)
		:setForegroundState("clicked", colors.gray)
		:setBackgroundState("clicked", colors.lightGray)
		:setSize(13, 4)
		:setPosition(2, 20)
end

setupLeft()
setupMiddle()
setupRight()

basalt.run()
